#!/bin/sh

#PBS -N uncsf_3 
#PBS -l ncpus=1
#PBS -l walltime=300:00:00 
#PBS -M francisco@icmc.usp.br

module load python/3.5.4

cd /home/francisco/epidemics

source ../libraries/bin/activate     #carrega a sua variavel de ambiente onde você instalou o numpy e o networkx

python SIR-Discrete-USair.py




